steps:
  - name: node:22
    entrypoint: npm
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "public", "gs://www.bradzellman.com"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "setmeta", "-h", "Cache-Control:no-cache, max-age=0", "gs://www.bradzellman.com/*.html", "gs://www.bradzellman.com/content/**", "gs://www.bradzellman.com/admin/**"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "setmeta", "-h", "Cache-Control:public, max-age=86400", "gs://www.bradzellman.com/images/**"]

options:
  logging: CLOUD_LOGGING_ONLY
